# Generated by Django 4.0.1 on 2022-01-27 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark', '0003_alter_bookmark_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='image',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='url',
            field=models.URLField(null=True),
        ),
    ]
